Localization
Elina-nep/graphiql-app pull request #19
Opened 2023-05-24 19:51 UTC by makhitr

2023-05-25 09:29 UTC, KarinaBertosh approved these changes

2023-05-25 13:34 UTC, Elina-nep commented on react-ts/public/locales/en/translation.json
> +  "welcome_page": {
сейчас в девелопе новая версия текста на главной странице, посмотри, пожалуйста

2023-05-25 13:38 UTC, Elina-nep requested changes
посмотри сейчас в ветке девелоп приветственную страницу, там есть изменения по тексту. Нам нужна информация о нашем приложении, а не оригинальном GQL

2023-05-26 14:57 UTC, Elina-nep approved these changes

2023-05-26 18:58 UTC, merged